import type { SummaryResponse } from "../lib/types";
import { Card } from "./Card";
import styles from "./SummaryPanel.module.css";

export function SummaryPanel({ summary }: { summary: SummaryResponse | null }) {
  return (
    <Card title="AI summary" aside={<span className={styles.tag}>Advisory, not a measurement</span>}>
      {summary === null && <p className={styles.pending}>Generating summary…</p>}
      {summary?.ok && (
        <>
          <p className={styles.text}>{summary.text}</p>
          {summary.provider && <small className={styles.provider}>Generated by {summary.provider}</small>}
        </>
      )}
      {summary && !summary.ok && (
        <p className={styles.unavailable}>
          <strong>Summary unavailable:</strong> {summary.error}
        </p>
      )}
    </Card>
  );
}
