import type { SummaryResponse } from "../lib/types";

export function SummaryPanel({ summary }: { summary: SummaryResponse | null }) {
  return (
    <section aria-label="AI summary">
      <h2>AI summary — advisory, not a measurement</h2>
      {summary === null && <p>Generating summary…</p>}
      {summary?.ok && (
        <>
          <p>{summary.text}</p>
          {summary.provider && <small>Generated by {summary.provider}</small>}
        </>
      )}
      {summary && !summary.ok && <p>Summary unavailable: {summary.error}</p>}
    </section>
  );
}
